### ISSUE TITLE
Vim Gundo plugin is broken

### ISSUE THREAD

**Issue by skazhy** [skazhy/dotfiles#23]
Errors with `unknown function: gundo#gundoShow` (same error for other gundo commands). With  `let g:gundo_prefer_python3 = 1` set:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/karlis/dotfiles/Vim/pack/plugins/start/gundo/autoload/gundo.py", line 472, in GundoRenderPreview
    _output_preview_text(_generate_preview_diff(current, node_before, node_after))
  File "/Users/karlis/dotfiles/Vim/pack/plugins/start/gundo/autoload/gundo.py", line 382, in _generate_preview_diff
    before_time, after_time))
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/difflib.py", line 1177, in unified_diff
    _check_types(a, b, fromfile, tofile, fromfiledate, tofiledate, lineterm)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/difflib.py", line 1312, in _check_types

TypeError: all arguments must be str, not: 1 
```

**Comment by skazhy** [comment]
Gundo removed for now.
